### ISSUE TITLE
I found a bug , RangeError: offset out of range

### ISSUE THREAD

**Issue by jangbian** [HtmlUnit/htmlunit-core-js#27]
![image](https://github.com/user-attachments/assets/4e88948a-337c-45d1-9c89-245449d46fed)
Why are the two judgment logics marked in the red box different?Is this a bug?In fact,this makes me throw the exception RangeError:offset out of range when running the js method,but my js code can run normally in the browser,and when I try to debug skip the judgment here,it can also run normally to calculate the correct result. Can you please check it?

**Comment by jangbian** [comment]
Problem with first method setRange ,【off>=this.length】 changed to 【off>this.length】will be right

**Comment by rbri** [comment]
Hm,
corrently i have no access to my hardware.
Second, this is a bug in rhino, i like to fix it there an then merge it into core-js.
And all this will lead to a new core- js snapshot built.

If it is really that important to have this fixed please think about sponsoring my work, this helps me when thinking about priorities.

Why do you need this that fast?

**Comment by rbri** [comment]
@jangbian pr for rhino is done, as soon at that is merged i will merge that change into core-js and build a new snapshot

**Comment by jangbian** [comment]
> @jangbian pr for rhino is done, as soon at that is merged i will merge that change into core-js and build a new snapshot
Thank you~

**Comment by rbri** [comment]
@jangbian you can try corejs 4.8.0-SNAPSHOT

**Comment by jangbian** [comment]
> @jangbian you can try corejs 4.8.0-SNAPSHOT

Could I ask you how to use 4.8.0-SNAPSHOT in maven ? like this ?

        <dependency>
            <groupId>org.htmlunit</groupId>
            <artifactId>htmlunit-core-js</artifactId>
            <version>4.8.0-SNAPSHOT</version>
        </dependency>

**Comment by rbri** [comment]
It"s simpler, just use htmlunit 4.8 snapshot. This will use the latest corejs build. But you have to add another repository location to your pom. Cheh the readme...

**Comment by jangbian** [comment]
> It"s simpler, just use htmlunit 4.8 snapshot. This will use the latest corejs build. But you have to add another repository location to your pom. Cheh the readme...
> 
> https://github.com/HtmlUnit/htmlunit?tab=readme-ov-file#maven-1

I get it! 
![image](https://github.com/user-attachments/assets/0439c3f4-82d9-4173-ac62-fca03f7e08b7)

**Comment by rbri** [comment]
And? Success?

**Comment by jangbian** [comment]
> And? Success?

Yes,it’s works now, I got the right result

**Comment by rbri** [comment]
Ok, great, thanks for reporting and all the digging into the core-js stuff to find this.
